set(CROSS_COMPILE ${IS_CROSS_COMPILING})
set(CMAKE_SYSTEM_NAME ${TARGET_SYSTEM})

set(CMAKE_SYSTEM_PROCESSOR ${TARGET_ARCH})

set(CMAKE_C_COMPILER    ${COMPILER_CC})
set(CMAKE_CXX_COMPILER  ${COMPILER_CXX})
set(CMAKE_AR			${COMPILER_AR})
set(CMAKE_LINKER		${COMPILER_LD})
set(CMAKE_NM			${COMPILER_NM})
set(CMAKE_OBJDUMP		${COMPILER_OBJDUMP})
set(CMAKE_RANLIB		${COMPILER_RANLIB})

set(ENV{PKG_CONFIG_PATH} "${LOCAL_DIR}/lib/pkgconfig")

set(CMAKE_FIND_ROOT_PATH ${LOCAL_DIR})

include_directories(${LOCAL_DIR}/include)
link_directories(${LOCAL_DIR}/lib)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
